[default]
"bootstrap.servers"="pkc-lgwgm.eastus2.azure.confluent.cloud:9092"
"security.protocol"="SASL_SSL"
"sasl.mechanisms"="PLAIN"
"sasl.username"="EMUBBQMU42ZKXMSY"
"sasl.password"="3H2fOGFoArTjHndfm87G/1bI2efP7vqmIuryI6FQS2MmTKdxr2sGSFBEKEg+2sCF"

[consumer]
"group.id"="python_example_group_1"
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
"auto.offset.reset"="earliest"